[build]
  command = "npm run build"  # Adjust this based on your build script
  functions = "functions"

[[redirects]]
  from = "/(.*)"
  to = "/build/server.js"
  status = 200

[build.environment]
  NODE_ENV = "production"
